export const categories = [
  {
    id: 'world-cup',
    name: 'منتخبات',
    subtitle: 'قسم خاص بمناسبة كأس العالم',
    accent: '#0d6f3c',
    badge: 'WC',
  },
  {
    id: 'men',
    name: 'رجال',
    subtitle: 'ستايل يومي ورياضي',
    accent: '#1d3557',
    badge: 'M',
  },
  {
    id: 'women',
    name: 'سيدات',
    subtitle: 'فساتين ولوك عصري',
    accent: '#7b2cbf',
    badge: 'W',
  },
  {
    id: 'girls',
    name: 'بنات',
    subtitle: 'ألوان مرحة وموديلات ناعمة',
    accent: '#ff6b9d',
    badge: 'G',
  },
  {
    id: 'kids',
    name: 'أطفال',
    subtitle: 'مريح وعملي للحركة',
    accent: '#ff9f1c',
    badge: 'K',
  },
  {
    id: 'shoes',
    name: 'جزم',
    subtitle: 'كاجوال وسبورت',
    accent: '#2a9d8f',
    badge: 'S',
  },
]

export const defaultProducts = [
  {
    id: 'wc-arg-home',
    name: 'طقم الأرجنتين الأساسي',
    nameAr: 'طقم الأرجنتين الأساسي',
    nameEn: 'Argentina home kit',
    category: 'world-cup',
    price: 1190,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'قماش خفيف مناسب للمباريات والتشجيع، مع تفاصيل مستوحاة من النسخة الرسمية.',
    descriptionAr:
      'قماش خفيف مناسب للمباريات والتشجيع، مع تفاصيل مستوحاة من النسخة الرسمية.',
    descriptionEn:
      'Lightweight match-ready fabric with premium details inspired by the official kit.',
    badge: 'الأكثر طلبًا',
    badgeAr: 'الأكثر طلبًا',
    badgeEn: 'Best seller',
    image:
      'linear-gradient(135deg, #0f172a 0%, #1d4ed8 35%, #93c5fd 100%)',
    createdAt: '2026-06-30T10:00:00.000Z',
  },
  {
    id: 'wc-brazil-away',
    name: 'تيشيرت البرازيل الاحتياطي',
    nameAr: 'تيشيرت البرازيل الاحتياطي',
    nameEn: 'Brazil away shirt',
    category: 'world-cup',
    price: 980,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'تصميم ملفت بدرجات الأزرق، مناسب للمشجعين ومحبي الستايل الرياضي.',
    descriptionAr: 'تصميم ملفت بدرجات الأزرق، مناسب للمشجعين ومحبي الستايل الرياضي.',
    descriptionEn: 'Bold blue tones designed for supporters who love standout sporty style.',
    badge: 'كأس العالم',
    badgeAr: 'كأس العالم',
    badgeEn: 'World Cup',
    image:
      'linear-gradient(135deg, #012a4a 0%, #0096c7 40%, #90e0ef 100%)',
    createdAt: '2026-06-30T10:05:00.000Z',
  },
  {
    id: 'men-urban-set',
    name: 'طقم رجالي كاجوال',
    nameAr: 'طقم رجالي كاجوال',
    nameEn: 'Men urban set',
    category: 'men',
    price: 760,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'قصة مريحة وخامة ناعمة مناسبة للخروج اليومي.',
    descriptionAr: 'قصة مريحة وخامة ناعمة مناسبة للخروج اليومي.',
    descriptionEn: 'Relaxed cut with a soft feel for everyday wear and quick outings.',
    badge: 'رجالي',
    badgeAr: 'رجالي',
    badgeEn: 'Men',
    image:
      'linear-gradient(135deg, #111827 0%, #374151 45%, #9ca3af 100%)',
    createdAt: '2026-06-30T10:10:00.000Z',
  },
  {
    id: 'women-elegant-dress',
    name: 'فستان سيدات أنيق',
    nameAr: 'فستان سيدات أنيق',
    nameEn: 'Elegant women dress',
    category: 'women',
    price: 1350,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'فستان ناعم بمظهر راقٍ مناسب للمشاوير والمناسبات الخفيفة.',
    descriptionAr: 'فستان ناعم بمظهر راقٍ مناسب للمشاوير والمناسبات الخفيفة.',
    descriptionEn: 'A refined dress with a polished silhouette for outings and light occasions.',
    badge: 'وصل جديد',
    badgeAr: 'وصل جديد',
    badgeEn: 'New arrival',
    image:
      'linear-gradient(135deg, #3d1f58 0%, #b5179e 45%, #f9bec7 100%)',
    createdAt: '2026-06-30T10:15:00.000Z',
  },
  {
    id: 'girls-bloom-set',
    name: 'طقم بنات مزهر',
    nameAr: 'طقم بنات مزهر',
    nameEn: 'Girls bloom set',
    category: 'girls',
    price: 540,
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'ألوان مبهجة وقماش مناسب للحركة واللعب.',
    descriptionAr: 'ألوان مبهجة وقماش مناسب للحركة واللعب.',
    descriptionEn: 'Cheerful colors and breathable fabric made for easy movement and play.',
    badge: 'بنات',
    badgeAr: 'بنات',
    badgeEn: 'Girls',
    image:
      'linear-gradient(135deg, #ff4d8d 0%, #ff85a1 40%, #ffd6e0 100%)',
    createdAt: '2026-06-30T10:20:00.000Z',
  },
  {
    id: 'kids-soft-pack',
    name: 'باك أطفال صيفي',
    nameAr: 'باك أطفال صيفي',
    nameEn: 'Kids summer pack',
    category: 'kids',
    price: 620,
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'قطعتان بخامة قطنية مريحة للأيام الطويلة.',
    descriptionAr: 'قطعتان بخامة قطنية مريحة للأيام الطويلة.',
    descriptionEn: 'A soft two-piece set in comfortable cotton for long active days.',
    badge: 'أطفال',
    badgeAr: 'أطفال',
    badgeEn: 'Kids',
    image:
      'linear-gradient(135deg, #f77f00 0%, #fcbf49 50%, #ffe8a1 100%)',
    createdAt: '2026-06-30T10:25:00.000Z',
  },
  {
    id: 'shoes-white-run',
    name: 'كوتشي أبيض كلاسيك',
    nameAr: 'كوتشي أبيض كلاسيك',
    nameEn: 'Classic white sneakers',
    category: 'shoes',
    price: 890,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'حذاء عملي يناسب اللبس اليومي واللوك الرياضي.',
    descriptionAr: 'حذاء عملي يناسب اللبس اليومي واللوك الرياضي.',
    descriptionEn: 'An easy everyday pair that fits casual looks and active styling.',
    badge: 'جزم',
    badgeAr: 'جزم',
    badgeEn: 'Shoes',
    image:
      'linear-gradient(135deg, #0f172a 0%, #475569 40%, #e2e8f0 100%)',
    createdAt: '2026-06-30T10:30:00.000Z',
  },
  {
    id: 'women-casual-set',
    name: 'طقم سيدات مريح',
    nameAr: 'طقم سيدات مريح',
    nameEn: 'Women comfort set',
    category: 'women',
    price: 840,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'ستايل بسيط وأنيق، مناسب للشغل والخروجات السريعة.',
    descriptionAr: 'ستايل بسيط وأنيق، مناسب للشغل والخروجات السريعة.',
    descriptionEn: 'Simple and polished styling that works for workdays and fast errands.',
    badge: 'سيدات',
    badgeAr: 'سيدات',
    badgeEn: 'Women',
    image:
      'linear-gradient(135deg, #5f0f40 0%, #9a031e 45%, #ffb5a7 100%)',
    createdAt: '2026-06-30T10:35:00.000Z',
  },
]
